version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
jobs:
  check-and-build-only:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
workflows:
  build-docker-image-only:
    jobs:
      - check-and-build-only
